name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest  

    permissions:
      id-token: write  
      contents: read   

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  

    - name: Configure AWS credentials using OIDC and IAM Identity Center
      uses: aws-actions/configure-aws-credentials@v2
      with:
        sso-start-url: ${{ secrets.AWS_SSO_START_URL }}
        sso-region: ${{ secrets.AWS_SSO_REGION }}
        sso-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
        sso-role-name: ${{ secrets.AWS_SSO_ROLE_NAME }}
        aws-region: eu-north-1  

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: ./terraform
