name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::713881800615:role/Github
        aws-region: eu-north-1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Import S3 Buckets if they exist
      run: |
        terraform import aws_s3_bucket.static_website website-bucket-23948989 || echo "Website bucket does not exist, skipping import"
        terraform import aws_s3_bucket.terraform_bucket terraform-state-bucket-239292 || echo "State bucket does not exist, skipping import"
      working-directory: ./terraform

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: ./terraform
